version: '3.3'
services:
 mysql:
  hostname: mysql
  # 启动容器名称mysql
  container_name: mysql
  # 使用mysql 5.7.20的镜像
  image: mysql:5.7.30
  # 自启动
  restart: always
  command:
    - --default-time_zone=+8:00 # mysql时间加8个小时
    - --character-set-server=utf8mb4 # mysql默认使用utf8mb4编码
    - --collation-server=utf8mb4_general_ci
    - --explicit_defaults_for_timestamp= true
    - --lower_case_table_names=1
    - --max_allowed_packet=128M
  environment:
   # 服务器时区使用上海 
   TZ: Asis/Shanghai
   # mysql初始化密码
   MYSQL_ROOT_PASSWORD: 1111
  ports:
   # 容器3306端口映射到宿主机3306端口
   - "3306:3306"
  volumes:
   # mysql相关数据存储在宿主机/data/docker/mysql文件夹
   - "./data/:/var/lib/mysql"